# WEEK 3
# Customer Sales Insights Using SQL

## Introduction

The Superstore dataset contains information about customer orders, products, sales, profits, and shipping details. In this project, SQL is used to analyze sales data and extract meaningful business insights. The dataset is first organized into separate tables for customers, orders, and products to improve data management and reduce redundancy.

## Objective

The objective of this project is to apply SQL concepts such as Subqueries, Common Table Expressions (CTEs), Window Functions, and Joins to analyze customer sales performance. The analysis aims to identify high-value customers, rank customers based on sales, evaluate purchasing behavior, and generate business insights from the Superstore dataset.

# Import required libraries

In [1]:
import pandas as pd
import sqlite3

# Step 1: Setup Data
# Load the Superstore dataset

In [3]:
df = pd.read_csv('superstore_raw.csv', encoding='latin1')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

# Create SQLite database connection

In [4]:
conn = sqlite3.connect('superstore.db')

# Store the dataset into a SQL table named superstore_raw

In [5]:
df.to_sql(
    'superstore_raw',
    conn,
    if_exists='replace',
    index=False
)

9994

In [6]:
pd.read_sql(
    "SELECT * FROM superstore_raw LIMIT 10",
    conn
)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

In [7]:
print(df.columns)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

# Create customers table using distinct customer records

In [8]:
conn.execute("""
CREATE TABLE customers AS
SELECT DISTINCT
    "Customer ID",
    "Customer Name",
    Segment
FROM superstore_raw
""")

In [9]:
pd.read_sql("SELECT * FROM customers LIMIT 5", conn)

  Customer ID    Customer Name    Segment
0    CG-12520      Claire Gute   Consumer
1    DV-13045  Darrin Van Huff  Corporate
2    SO-20335   Sean O'Donnell   Consumer
3    BH-11710  Brosina Hoffman   Consumer
4    AA-10480     Andrew Allen   Consumer

# Create products table using distinct product information

In [10]:
conn.execute("""
CREATE TABLE products AS
SELECT DISTINCT
    "Product ID",
    "Product Name",
    Category,
    "Sub-Category"
FROM superstore_raw
""")

In [11]:
pd.read_sql("SELECT * FROM products LIMIT 5", conn)

,Product ID,Product Name,Category,Sub-Category
0,FUR-BO-10001798,Bush Somerset Collection Bookcase,Furniture,Bookcases
1,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture,Chairs
2,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,Office Supplies,Labels
3,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,Furniture,Tables
4,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,Office Supplies,Storage

# Create orders table using distinct order details

In [12]:
conn.execute("""
CREATE TABLE orders AS
SELECT DISTINCT
    "Order ID",
    "Order Date",
    "Ship Date",
    "Customer ID",
    Sales,
    Quantity,
    Profit
FROM superstore_raw
""")

In [13]:
pd.read_sql("SELECT * FROM orders LIMIT 5", conn)

,Order ID,Order Date,Ship Date,Customer ID,Sales,Quantity,Profit
0,CA-2016-152156,11/8/2016,11/11/2016,CG-12520,261.9600,2,41.9136
1,CA-2016-152156,11/8/2016,11/11/2016,CG-12520,731.9400,3,219.5820
2,CA-2016-138688,6/12/2016,6/16/2016,DV-13045,14.6200,2,6.8714
3,US-2015-108966,10/11/2015,10/18/2015,SO-20335,957.5775,5,-383.0310
4,US-2015-108966,10/11/2015,10/18/2015,SO-20335,22.3680,2,2.5164

#Brief Insight :
The Superstore dataset was loaded into the superstore_raw table. Using SELECT DISTINCT, separate customer, product, and order tables were created to reduce duplication and organize the data into meaningful entities.



#Step 2: Performing Required Queries

# Query 1: Find orders with sales greater than average sales

In [14]:
pd.read_sql("""
SELECT *
FROM orders
WHERE Sales > (
    SELECT AVG(Sales)
    FROM orders
)
""", conn)

,Order ID,Order Date,Ship Date,Customer ID,Sales,Quantity,Profit
0,CA-2016-152156,11/8/2016,11/11/2016,CG-12520,261.9600,2,41.9136
1,CA-2016-152156,11/8/2016,11/11/2016,CG-12520,731.9400,3,219.5820
2,US-2015-108966,10/11/2015,10/18/2015,SO-20335,957.5775,5,-383.0310
3,CA-2014-115812,6/9/2014,6/14/2014,BH-11710,907.1520,6,90.7152
4,CA-2014-115812,6/9/2014,6/14/2014,BH-11710,1706.1840,9,85.3092
...,...,...,...,...,...,...,...
2354,US-2016-103674,12/6/2016,12/10/2016,AP-10720,271.9600,5,27.1960
2355,US-2016-103674,12/6/2016,12/10/2016,AP-10720,249.5840,2,31.1980
2356,US-2016-103674,12/6/2016,12/10/2016,AP-10720,437.4720,14,153.1152
2357,CA-2017-121258,2/26/2017,3/3/2017,DB-13060,258.5760,2,19.3932
2358,CA-2017-119914,5/4/2017,5/9/2017,CC-12220,243.1600,2,72.9480

#Insight:
These orders have sales values higher than the overall average sales, indicating above-average transactions.

# Query 2 : Find highest sales order for each customer

In [15]:
pd.read_sql("""
SELECT *
FROM orders o
WHERE Sales = (
    SELECT MAX(Sales)
    FROM orders
    WHERE "Customer ID" = o."Customer ID"
)
""", conn)

,Order ID,Order Date,Ship Date,Customer ID,Sales,Quantity,Profit
0,CA-2016-152156,11/8/2016,11/11/2016,CG-12520,731.9400,3,219.5820
1,US-2015-108966,10/11/2015,10/18/2015,SO-20335,957.5775,5,-383.0310
2,CA-2014-115812,6/9/2014,6/14/2014,BH-11710,1706.1840,9,85.3092
3,CA-2015-106320,9/25/2015,9/30/2015,EB-13870,1044.6300,3,240.2649
4,US-2015-150630,9/17/2015,9/21/2015,TB-21520,3083.4300,7,-1665.0522
...,...,...,...,...,...,...,...
790,CA-2015-159534,3/20/2015,3/23/2015,DH-13075,1087.9360,8,353.5792
791,CA-2016-129630,9/4/2016,9/4/2016,IM-15055,2799.9600,5,944.9865
792,CA-2017-121559,6/1/2017,6/3/2017,HW-14935,2405.2000,8,793.7160
793,CA-2017-153871,12/11/2017,12/17/2017,RB-19435,735.9800,2,331.1910
794,US-2016-103674,12/6/2016,12/10/2016,AP-10720,437.4720,14,153.1152

#Insight:
This query identifies the largest purchase made by each customer.

# Query 3 : Calculate total sales for each customer using CTE

In [16]:
pd.read_sql("""
WITH customer_sales AS (
    SELECT
        "Customer ID",
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY "Customer ID"
)
SELECT *
FROM customer_sales
ORDER BY total_sales DESC
""", conn)

    Customer ID  total_sales
0      SM-20320    25043.050
1      TC-20980    19052.218
2      RB-19360    15117.339
3      TA-21385    14595.620
4      AB-10105    14473.571
..          ...          ...
788    RS-19870       22.328
789    MG-18205       16.739
790    CJ-11875       16.520
791    LD-16855        5.304
792    TS-21085        4.833

[793 rows x 2 columns]

#Insight:
The CTE calculates cumulative sales generated by each customer.

# Query 4 : Find customers whose total sales are above average

In [17]:
pd.read_sql("""
WITH customer_sales AS (
    SELECT
        "Customer ID",
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY "Customer ID"
)
SELECT *
FROM customer_sales
WHERE total_sales >
(
    SELECT AVG(total_sales)
    FROM customer_sales
)
ORDER BY total_sales DESC
""", conn)

    Customer ID  total_sales
0      SM-20320    25043.050
1      TC-20980    19052.218
2      RB-19360    15117.339
3      TA-21385    14595.620
4      AB-10105    14473.571
..          ...          ...
289    JK-16120     2932.484
290    SW-20455     2921.544
291    ML-17410     2921.500
292    RD-19585     2912.894
293    CY-12745     2900.026

[294 rows x 2 columns]

#Insight:
These customers contribute more sales than the average customer and are high-value customers.

# Query 5 : Rank customers based on total sales

In [18]:
pd.read_sql("""
WITH customer_sales AS (
    SELECT
        "Customer ID",
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY "Customer ID"
)
SELECT
    "Customer ID",
    total_sales,
    RANK() OVER (ORDER BY total_sales DESC) AS sales_rank
FROM customer_sales
""", conn)

    Customer ID  total_sales  sales_rank
0      SM-20320    25043.050           1
1      TC-20980    19052.218           2
2      RB-19360    15117.339           3
3      TA-21385    14595.620           4
4      AB-10105    14473.571           5
..          ...          ...         ...
788    RS-19870       22.328         789
789    MG-18205       16.739         790
790    CJ-11875       16.520         791
791    LD-16855        5.304         792
792    TS-21085        4.833         793

[793 rows x 3 columns]

#Insight:
Customers are ranked according to their total contribution to sales revenue.

# Query 6 : Assign row numbers to orders within each customer

In [19]:
pd.read_sql("""
SELECT
    "Customer ID",
    "Order ID",
    Sales,
    ROW_NUMBER() OVER (
        PARTITION BY "Customer ID"
        ORDER BY Sales DESC
    ) AS row_num
FROM orders
""", conn)

     Customer ID        Order ID     Sales  row_num
0       AA-10315  CA-2016-103982  3930.072        1
1       AA-10315  CA-2014-128055   673.568        2
2       AA-10315  CA-2016-103982   431.976        3
3       AA-10315  CA-2017-147039   362.940        4
4       AA-10315  CA-2014-128055    52.980        5
...          ...             ...       ...      ...
9988    ZD-21925  CA-2017-141481    61.440        5
9989    ZD-21925  CA-2014-143336    22.720        6
9990    ZD-21925  US-2016-147991    16.720        7
9991    ZD-21925  CA-2016-152471    15.984        8
9992    ZD-21925  CA-2014-143336     8.560        9

[9993 rows x 4 columns]

#Insight:
Each customer's orders are numbered separately based on sales value.

# Query 7 : Display top 3 customers based on total sales

In [20]:
pd.read_sql("""
WITH customer_sales AS (
    SELECT
        "Customer ID",
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY "Customer ID"
),
ranked_customers AS (
    SELECT
        "Customer ID",
        total_sales,
        RANK() OVER (
            ORDER BY total_sales DESC
        ) AS sales_rank
    FROM customer_sales
)
SELECT *
FROM ranked_customers
WHERE sales_rank <= 3
""", conn)

  Customer ID  total_sales  sales_rank
0    SM-20320    25043.050           1
1    TC-20980    19052.218           2
2    RB-19360    15117.339           3

#Insight:
These are the top-performing customers based on total sales generated.

#Brief Insight :
In this step, SQL techniques such as Subqueries, Common Table Expressions (CTEs), and Window Functions were used to analyze customer sales data. The queries helped identify high-value transactions, calculate total customer sales, determine customers with above-average performance, and rank customers based on revenue contribution. These analyses provide valuable insights into customer purchasing patterns and overall sales performance.

#Step 3: Final Combined Query

# Combine JOIN, CTE and Window Function
# Query : Display customer name, total sales and rank

In [21]:
pd.read_sql("""
WITH customer_sales AS (
    SELECT
        "Customer ID",
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY "Customer ID"
)

SELECT
    c."Customer Name",
    cs.total_sales,
    RANK() OVER (
        ORDER BY cs.total_sales DESC
    ) AS sales_rank
FROM customer_sales cs
JOIN customers c
ON cs."Customer ID" = c."Customer ID"
ORDER BY sales_rank
""", conn)

       Customer Name  total_sales  sales_rank
0        Sean Miller    25043.050           1
1       Tamara Chand    19052.218           2
2       Raymond Buch    15117.339           3
3       Tom Ashbrook    14595.620           4
4      Adrian Barton    14473.571           5
..               ...          ...         ...
788       Roy Skaria       22.328         789
789  Mitch Gastineau       16.739         790
790     Carl Jackson       16.520         791
791     Lela Donovan        5.304         792
792    Thais Sissman        4.833         793

[793 rows x 3 columns]

#Brief Insight :
The query combines a CTE, JOIN, and Window Function to calculate total sales for each customer and rank them based on their contribution to revenue. Customers with higher total sales receive a better rank.

# MINI PROJECT

# Query 1 :Find the top 5 customers based on total sales generated

In [22]:
pd.read_sql("""
WITH customer_sales AS (
    SELECT
        "Customer ID",
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY "Customer ID"
)

SELECT
    c."Customer Name",
    cs.total_sales
FROM customer_sales cs
JOIN customers c
ON cs."Customer ID" = c."Customer ID"
ORDER BY cs.total_sales DESC
LIMIT 5
""", conn)

   Customer Name  total_sales
0    Sean Miller    25043.050
1   Tamara Chand    19052.218
2   Raymond Buch    15117.339
3   Tom Ashbrook    14595.620
4  Adrian Barton    14473.571

#Insight

These customers generated the highest revenue and can be considered the most valuable customers.

# Query 2 : Find the bottom 5 customers based on total sales

In [23]:
pd.read_sql("""
WITH customer_sales AS (
    SELECT
        "Customer ID",
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY "Customer ID"
)

SELECT
    c."Customer Name",
    cs.total_sales
FROM customer_sales cs
JOIN customers c
ON cs."Customer ID" = c."Customer ID"
ORDER BY cs.total_sales ASC
LIMIT 5
""", conn)

     Customer Name  total_sales
0    Thais Sissman        4.833
1     Lela Donovan        5.304
2     Carl Jackson       16.520
3  Mitch Gastineau       16.739
4       Roy Skaria       22.328

#Insight

These customers contributed the least sales and may require engagement strategies to increase purchases.

# Query 3 : Identify customers who placed only one order

In [24]:
pd.read_sql("""
SELECT
    c."Customer Name",
    COUNT(o."Order ID") AS order_count
FROM customers c
JOIN orders o
ON c."Customer ID" = o."Customer ID"
GROUP BY c."Customer ID", c."Customer Name"
HAVING COUNT(o."Order ID") = 1
""", conn)

       Customer Name  order_count
0  Anthony O'Donnell            1
1       Carl Jackson            1
2     Jocasta Rupert            1
3       Lela Donovan            1
4    Ricardo Emerson            1

#Insight

These customers placed only one order during the period and may represent one-time buyers.

# Query 4 : Find customers whose total sales are greater than the average customer sales

In [25]:
pd.read_sql("""
WITH customer_sales AS (
    SELECT
        "Customer ID",
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY "Customer ID"
)

SELECT
    c."Customer Name",
    cs.total_sales
FROM customer_sales cs
JOIN customers c
ON cs."Customer ID" = c."Customer ID"
WHERE cs.total_sales >
(
    SELECT AVG(total_sales)
    FROM customer_sales
)
ORDER BY cs.total_sales DESC
""", conn)

     Customer Name  total_sales
0      Sean Miller    25043.050
1     Tamara Chand    19052.218
2     Raymond Buch    15117.339
3     Tom Ashbrook    14595.620
4    Adrian Barton    14473.571
..             ...          ...
289     Julie Kriz     2932.484
290    Shaun Weien     2921.544
291   Maris LaWare     2921.500
292       Rob Dowd     2912.894
293   Craig Yedwab     2900.026

[294 rows x 2 columns]

#Insight

These customers spend more than the average customer and are important contributors to revenue.

# Query 5 : Find the highest order value placed by each customer

In [26]:
pd.read_sql("""
SELECT
    c."Customer Name",
    MAX(o.Sales) AS highest_order_value
FROM customers c
JOIN orders o
ON c."Customer ID" = o."Customer ID"
GROUP BY c."Customer ID", c."Customer Name"
ORDER BY highest_order_value DESC
""", conn)

       Customer Name  highest_order_value
0        Sean Miller            22638.480
1       Tamara Chand            17499.950
2       Raymond Buch            13999.960
3       Tom Ashbrook            11199.968
4       Hunter Lopez            10499.970
..               ...                  ...
788     Carl Jackson               16.520
789  Mitch Gastineau               12.320
790       Roy Skaria                9.648
791     Lela Donovan                5.304
792    Thais Sissman                2.808

[793 rows x 2 columns]

#Insight

This shows the maximum value of a single order placed by each customer.

#Mini Project Conclusion

The analysis identified top and bottom customers based on sales, customers with only one purchase, customers whose sales exceed the average, and the highest-value order placed by each customer. These insights can help businesses target high-value customers, improve retention strategies, and understand purchasing behavior.

#Overall Conclusion

This project analyzed the Superstore dataset using SQL concepts such as Subqueries, Common Table Expressions (CTEs), Window Functions, and Joins. The dataset was first organized into separate customer, order, and product tables using SELECT DISTINCT to reduce redundancy and improve data management.

Through the analysis, orders with above-average sales were identified, the highest-value order for each customer was determined, and total sales were calculated to evaluate customer performance. Window functions were used to rank customers based on sales and assign row numbers to orders within each customer group. Additionally, business-focused queries helped identify the top and bottom customers, customers with only one order, customers whose sales exceeded the average, and the highest order value per customer.

Overall, the project demonstrates how SQL can be used to transform raw sales data into meaningful business insights. The results highlight customer purchasing patterns, revenue contribution, and customer rankings, which can support data-driven decision-making and customer relationship strategies.