# Import Libraries

In [ ]:
import pandas as pd

#Load Dataset

In [ ]:
df = pd.read_csv("/content/Combined_dataset.csv")

#Data Exploration

In [ ]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [ ]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [ ]:
df.shape

(1000, 24)

In [ ]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [ ]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

# Missing Value Handling

In [ ]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [ ]:
df.ffill(inplace=True)

In [ ]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   0
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       23
seller_name                5
sizes                      0
videos                     0
seller_information         5
variations                 0
best_offer                 0
more_offers                0
category                   0
dtype: int64

columns may contain:

empty strings "",
spaces " ",
text like "None"
or real null values mixed together.

So even after fillna(), pandas still counts some missing-like values.

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

#Basic Operations

In [ ]:
df[['title', 'rating', 'final_price']]

                       title  rating   final_price
23          The Souled Store     4.5     "₹367.00"
24                    Jockey     4.4     "₹579.00"
25   GROVERSONS Paris Beauty     4.0     "₹299.00"
26                     Susie     4.3     "₹374.00"
27                    Zivame     4.3     "₹499.00"
..                       ...     ...           ...
995                    KREDO     3.5  "₹11,890.00"
996                    GUESS     5.0   "₹8,900.00"
997                 GIORDANO     2.8   "₹7,950.00"
998                 Fastrack     4.3   "₹2,636.00"
999                  BOLDFIT     3.8     "₹699.00"

[977 rows x 3 columns]

In [ ]:
high_rating = df[df['rating'] > 4]
high_rating

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
23,17372928,The Souled Store,Men Blue & White Abstract Printed Boxers,4.5,22,799,54.0,"""₹367.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",THE███ULE███TOR█████████D.,"[{""size"":""S"",""value"":""30.0in"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...","F6 ███02,███umi█████████dus███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",boxers
24,15115018,Jockey,Non-Wired Non-Padded Combed Cotton Workout Bra...,4.4,1582,579,54.0,"""₹579.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"{""1_star"":90,""2_stars"":25,""3_stars"":93,""4_star...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███m R███il,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Ov...","[""https://videos.myntassets.com/assets/videos/...",Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
26,19219450,Susie,Black Solid Cotton T-Shirt Bra - Anti-Odour,4.3,12,749,50.0,"""₹374.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",GEN███AD ███AIL█████████LIM██████,"[{""size"":""30B"",""value"":""31.0in to 32.0in"",""val...","[""https://videos.myntassets.com/assets/videos/...",2ND███OOR███O 1█████████MAL███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
27,22196924,Zivame,Underwired Lightly Padded Pushup Bra,4.3,118,999,50.0,"""₹499.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":6,""2_stars"":7,""3_stars"":8,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",MIL███AR ███AIL█████████LIM██████,"[{""size"":""30A"",""value"":""31.0in"",""value_name"":""...","[""https://videos.myntassets.com/assets/videos/...",MIL███TAR███TAI█████████ LI███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
30,19277544,Marks & Spencer,BOUTIQUE X DAMARIS Navy Blue Underwired Lightl...,4.3,24,2999,60.0,"""₹2,249.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Ret███Net███,"[{""size"":""32B"",""value"":""34.0in"",""value_name"":""...","[""https://videos.myntassets.com/assets/videos/...",Blo███B-1███abi█████████-24███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.0,"""₹3,266.00""",INR,http://assets.myntassets.com/assets/images/246...,...,"{""1_star"":56,""2_stars"":21,""3_stars"":42,""4_star...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","Fir███Flo███ Pl█████████, I███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.0,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Fla███ech███tai███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","3rd███165███th █████████, s███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/848...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":8,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Br ███erp███es,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",Kha███ no███122█████████lhi██████████████████,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Br ███erp███es,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Kha███ no███122█████████lhi██████████████████,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches

# Remove Duplicates

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(977, 24)

As the dataset did not include a quantity column, a quantity column was created and used to calculate total_amount.

In [ ]:
df['quantity'] = 2
df['total_amount'] = df['final_price'] * df['quantity']

In [ ]:

df[['final_price', 'quantity', 'total_amount']].head()

   final_price  quantity        total_amount
23   "₹367.00"         2  "₹367.00""₹367.00"
24   "₹579.00"         2  "₹579.00""₹579.00"
25   "₹299.00"         2  "₹299.00""₹299.00"
26   "₹374.00"         2  "₹374.00""₹374.00"
27   "₹499.00"         2  "₹499.00""₹499.00"

In [ ]:
df[['final_price', 'quantity']].dtypes

final_price    object
quantity        int64
dtype: object

The final_price column was originally stored as a string/object data type because it contained currency symbols (₹) and commas. To perform mathematical operations and create the total_amount column, the unwanted symbols were removed and the data type was converted to float. This allowed accurate numerical calculations using the price values.

In [ ]:
df['final_price'] = df['final_price'].str.replace('₹', '', regex=False)

df['final_price'] = df['final_price'].str.replace('"', '', regex=False)

df['final_price'] = df['final_price'].str.replace(',', '', regex=False)

df['final_price'] = df['final_price'].astype(float)

In [ ]:
df['final_price'].head()

23    367.0
24    579.0
25    299.0
26    374.0
27    499.0
Name: final_price, dtype: float64

# Derived Column

In [ ]:
df['total_amount'] = df['final_price'] * df['quantity']

In [ ]:
df[['final_price', 'quantity', 'total_amount']].head()

    final_price  quantity  total_amount
23        367.0         2         734.0
24        579.0         2        1158.0
25        299.0         2         598.0
26        374.0         2         748.0
27        499.0         2         998.0

# Save Cleaned Dataset

In [ ]:
df.to_csv("cleaned_dataset.csv", index=False)

## Summary:-

- Loaded shopping dataset using Pandas.
- Explored dataset using head(), tail(), shape, columns and dtypes.
- Identified and handled missing values.
- Selected important columns and filtered rows.
- Removed duplicate records.
- Created derived column total_amount using price × quantity.
- Saved cleaned dataset as cleaned_dataset.csv.