In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/dresses.csv")

In [3]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21664722,Curvy Clan,Colourblocked A-Line Cotton Maxi Dress,3.7,3,2999.0,NaN,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,RUB███S C███,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""B...",NaN,"604███TH ███OR,█████████ITA███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
1,21426422,Trendyol,Black Maxi Dress,4.1,10,4399.0,45.0,"""₹2,419.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
2,21238004,COVER STORY,Embellished Shoulder Straps Velvet Sheath Dress,4.8,24,3490.0,40.0,"""₹2,094.00""",INR,http://assets.myntassets.com/assets/images/212...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Cov███Sto███Clo█████████ite███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Kil███5/1███ 18█████████ 22███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
3,21426632,Trendyol,Floral Printed Shoulder strap A-Line Mini Dress,3.9,35,3599.0,30.0,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":6,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
4,21673378,RACHNA,Floral Print Flared Sleeve Crepe A-Line Mini D...,3.0,4,1299.0,51.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,RAC███ AR███RIN█████████TD.███,"[{""size"":""M"",""value"":""38.0in"",""value_name"":""Bu...",NaN,243███244███ Pa█████████rat█████████████████████,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

In [4]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
95,22630128,NUEVOSDAMAS,Girls Polka Dot Printed Crepe Fit & Flare Dress,2.8,5,1999.0,70.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,M/S███V M███C.,"[{""size"":""2-3Y"",""value"":""22.0in"",""value_name"":...",NaN,"D-2███09,███CTO█████████ , █████████████████████1",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
96,22610562,NIGHTSPREE,Band Collar Floral Printed Maternity Fit & Fla...,0.0,0,2299.0,50.0,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,MAH███R E███RPR██████,"[{""size"":""M"",""value"":""48.0in"",""value_name"":""Fr...",NaN,"C B███K, ███ FL█████████HEB███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
97,22596522,Vero Moda,Shoulder Straps Cut Out Smocked A-Line Midi Dress,4.3,12,3799.0,65.0,"""₹1,329.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",VER███ODA███TAI█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,4th███oor███he █████████ide███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
98,22619942,Styli,Burgundy Puff Sleeve Accordion Pleated Fit & F...,3.7,11,2799.0,51.0,"""₹1,371.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",PRE███RE ███AIL█████████PRI███████████████,"[{""size"":""S"",""value"":""33.1in"",""value_name"":""To...",NaN,KHA███ NO███/13█████████8/2███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
99,13400194,Style Quotient,Girls Navy Blue Striped Drop-Waist Dress,0.0,0,1299.0,73.0,"""₹350.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Kri███n S███het█████████td,"[{""size"":""2-3Y"",""value"":""9.0in"",""value_name"":""...",NaN,"615███hur███ate█████████,5 ███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

In [5]:
df.shape

(100, 24)

In [6]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [7]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [8]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   8
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       37
seller_name               10
sizes                      0
videos                    90
seller_information        10
variations                61
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [10]:
df.ffill(inplace=True)

In [14]:
df.dropna(inplace=True)

In [15]:
df[['final_price', 'discount']]

    final_price  discount
21  "₹1,750.00"      59.0
22    "₹597.00"      74.0
23    "₹849.00"      66.0
24    "₹379.00"      80.0
25  "₹1,599.00"      80.0
..          ...       ...
95    "₹599.00"      70.0
96  "₹1,149.00"      50.0
97  "₹1,329.00"      65.0
98  "₹1,371.00"      51.0
99    "₹350.00"      73.0

[79 rows x 2 columns]

In [19]:
high_discount = df[df['discount'] > 70.0]
high_discount

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
22,18803110,Athena Girl,Yellow Floral Dress,3.5,6,2299.0,74.0,"""₹597.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...","[{""percentage"":""77"",""value_name"":""Fit, Just Ri...",APE███PPA███S,"[{""size"":""10-11Y"",""value"":""2.25in"",""value_name...","[""https://videos.myntassets.com/assets/videos/...","Plo███o. ███, P█████████2Se███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
24,18951632,Berrylush,Women White Floral Pattern Play Dress,3.9,69,1899.0,80.0,"""₹379.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":13,""2_stars"":2,""3_stars"":5,""4_stars""...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""S"",""value"":""33.0in"",""value_name"":""Fr...","[""https://videos.myntassets.com/assets/videos/...",Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
25,18956684,Forevermore,Mustard Yellow Chiffon Embroidred Ruffle Tiere...,4.2,5,1599.0,80.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Ami███nte███ise███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...","[""https://videos.myntassets.com/assets/videos/...",10/███CHH███YA █████████ILL███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
26,18981160,Amydus,Blue & Orange Floral Wrap Dress,4.7,43,2799.0,80.0,"""₹2,799.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",BEG███01 ███EST██████,"[{""size"":""XXL"",""value"":""41.0in"",""value_name"":""...","[""https://videos.myntassets.com/assets/videos/...","357███has███, U█████████r, ███████████████████...","[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
36,17592092,U&F,Women Stylish Mustard Solid All in the Details...,4.1,7,2899.0,74.0,"""₹753.00""",INR,http://assets.myntassets.com/assets/images/175...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",SVP███XPO███ PR█████████ITE███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-13770986_cae700""]","A-4███ect███7 N█████████ , █████████████████████1","[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
50,19987092,Vastralay,Grey & Black Tie and Dye Dyed Midi Dress,4.2,17,2999.0,78.0,"""₹659.00""",INR,http://assets.myntassets.com/assets/images/199...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",ASH███ PR███S,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...","[""rw-19213302_cae700""]","ASH███ PR███S, █████████CTO███████████████████...","[{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
57,13703862,Style Quotient,Women Olive Green Solid Shirt Dress,3.9,46,1749.0,71.0,"""₹507.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":6,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Kri███n S███het█████████td,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-19513066_cae700""]","615███hur███ate█████████,5 ███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
58,18975316,Berrylush,Women Off-White Striped Knits Bits Dress,4.2,31,3200.0,74.0,"""₹640.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":4,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Sup███om ███,"[{""size"":""S"",""value"":""33.0in"",""value_name"":""Fr...","[""rw-19513066_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
71,13487998,THREAD MUSTER,Women Maroon Solid Maxi Dress,2.7,10,2499.0,74.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""34"",""value_name"":""Fit, Just Ri...",Wes███ry ███din█████████d_P████████████,"[{""size"":""S"",""value"":""33.0in"",""value_name"":""To...","[""rw-13649832_cae700""]",Wes███ry ███din█████████e L███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses
79,13406942,Global Desi,Girls Blue Embroidered A-Line Denim Dress,4.8,8,1799.0,75.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""65"",""value_name"":""Fit, Just Ri...",OCH███AND███ACK█████████LIM██████,"[{""size"":""3-4Y"",""value"":""21.0in"",""value_name"":...","[""rw-13586818_cae700""]",Bui███ng ███rat█████████eam███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
86,13382036,plusS,Women Olive Green Accordion Pleated Midi A-Lin...,4.2,623,1899.0,83.0,"""₹322.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":47,""2_stars"":31,""3_stars"":60,""4_star...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",Shi███Int███ati█████████rel███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...","[""rw-13586818_cae700""]",Fir███and███con█████████A 3███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
99,13400194,Style Quotient,Girls Navy Blue Striped Drop-Waist Dress,0.0,0,1299.0,73.0,"""₹350.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Kri███n S███het█████████td,"[{""size"":""2-3Y"",""value"":""9.0in"",""value_name"":""...","[""rw-13586818_cae700""]","615███hur███ate█████████,5 ███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

In [20]:
df.drop_duplicates(inplace=True)

In [22]:
df['quantity'] = 3
df['total_amount'] = df['final_price'] * df['quantity']

In [23]:
df['final_price'] = df['final_price'].str.replace('₹', '', regex=False)

df['final_price'] = df['final_price'].str.replace('"', '', regex=False)

df['final_price'] = df['final_price'].str.replace(',', '', regex=False)

df['final_price'] = df['final_price'].astype(float)

In [24]:
df['final_price'].head()

21    1750.0
22     597.0
23     849.0
24     379.0
25    1599.0
Name: final_price, dtype: float64

In [25]:
df['total_amount'] = df['final_price'] * df['quantity']

In [26]:
df[['final_price', 'quantity', 'total_amount']].head()

    final_price  quantity  total_amount
21       1750.0         3        5250.0
22        597.0         3        1791.0
23        849.0         3        2547.0
24        379.0         3        1137.0
25       1599.0         3        4797.0

In [28]:
df.to_csv("cleaned_dataset(dresses).csv", index=False)

# Summary

- Loaded shopping dataset using Pandas.
- Explored dataset using head(), tail(), shape, columns and dtypes.
- Identified and handled missing values.
- Selected important columns and filtered rows.
- Removed duplicate records.
- Created derived column total_amount using price × quantity.
- Saved cleaned dataset as cleaned_dataset.csv.