WEEK_8 AYUSHI GUPTA

In [ ]:
!pip install faker

Collecting faker
  Downloading faker-40.28.1-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.28.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 28.0 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.28.1

In [ ]:
import pandas as pd
import random
from faker import Faker

fake = Faker()

In [ ]:
customers = []

for i in range(1, 501):

    email = fake.email()

    customers.append({
        "customer_id": i,
        "customer_name": fake.name(),
        "email": email,
        "registration_date": fake.date(),
        "customer_type": random.choice(
            ["REGULAR", "PREMIUM", "VIP"]
        )
    })

customers = pd.DataFrame(customers)
customers.head()

,customer_id,customer_name,email,registration_date,customer_type
0,1,Kathy Hampton,danielnelson@example.com,1973-12-24,REGULAR
1,2,Joshua Gonzalez,hboyer@example.org,1981-07-10,PREMIUM
2,3,Terrence Mccarthy,collinsdarlene@example.net,1982-02-23,VIP
3,4,Lance Campbell,adamcarter@example.net,2002-09-11,VIP
4,5,Michael Brown,berrymichael@example.org,2006-12-19,VIP

In [ ]:
bad_rows = random.sample(range(500), 10)

for i in bad_rows:
    customers.loc[i, "email"] = "invalidemail.com"

In [ ]:
customers.head(15)

,customer_id,customer_name,email,registration_date,customer_type
0,1,Kathy Hampton,danielnelson@example.com,1973-12-24,REGULAR
1,2,Joshua Gonzalez,hboyer@example.org,1981-07-10,PREMIUM
2,3,Terrence Mccarthy,collinsdarlene@example.net,1982-02-23,VIP
3,4,Lance Campbell,adamcarter@example.net,2002-09-11,VIP
4,5,Michael Brown,berrymichael@example.org,2006-12-19,VIP
5,6,Stephanie Gaines,fharris@example.org,2005-03-31,PREMIUM
6,7,Debra Williams,angelareilly@example.org,1989-12-17,PREMIUM
7,8,Fred Weeks,heather52@example.org,1984-01-02,VIP
8,9,Jose Salazar,williamsscott@example.net,2026-04-09,VIP
9,10,Timothy Gutierrez,coreyrichards@example.net,2010-04-05,VIP
10,11,Eric Turner,stephensmichelle@example.com,2019-02-23,VIP
11,12,Nicholas Horne,angelawashington@example.net,1974-06-24,REGULAR
12,13,Madeline Carlson,uwalker@example.org,2021-05-25,REGULAR
13,14,Leslie Richardson,carly74@example.org,2020-06-03,PREMIUM
14,15,Terry Bradford,jessica26@example.org,1995-02-13,VIP

In [ ]:
duplicates = customers.sample(5)

customers = pd.concat(
    [customers, duplicates],
    ignore_index=True
)

In [ ]:
customers.shape

(505, 5)

In [ ]:
customers.to_csv(
    "customers.csv",
    index=False
)

In [ ]:
from google.colab import files
files.download("customers.csv")

In [ ]:
categories = [
    "Electronics",
    "Clothing",
    "Home",
    "Books"
]

products = []

for i in range(1, 501):

    products.append({
        "product_id": i,
        "product_name": fake.word(),
        "category": random.choice(categories),
        "subcategory": fake.word(),
        "cost_price": random.randint(100, 5000)
    })

products = pd.DataFrame(products)
products.head()

   product_id product_name     category subcategory  cost_price
0           1        break         Home      policy         397
1           2        leave        Books        film         749
2           3        scene         Home   establish         775
3           4         yeah  Electronics        hair        2169
4           5         main  Electronics         let        3613

In [ ]:
for i in random.sample(range(500), 20):

    name = products.loc[i, "product_name"]

    products.loc[i, "product_name"] = (
        "   " + name.upper() + "   "
    )

In [ ]:
products.to_csv(
    "products.csv",
    index=False
)

In [ ]:
from google.colab import files
files.download("products.csv")

In [ ]:
orders = []

statuses = [
    "PLACED",
    "SHIPPED",
    "DELIVERED",
    "CANCELLED",
    "RETURNED"
]

regions = [
    "NORTH",
    "SOUTH",
    "EAST",
    "WEST"
]

for i in range(1, 1001):

    orders.append({
        "order_id": i,
        "customer_id": random.randint(1, 500),
        "order_date": fake.date_time_between(
            start_date="-2y",
            end_date="now"
        ).strftime("%Y-%m-%d %H:%M:%S"),
        "status": random.choice(statuses),
        "region_code": random.choice(regions)
    })

orders = pd.DataFrame(orders)
orders.head()

   order_id  customer_id           order_date     status region_code
0         1            6  2025-05-01 09:16:57  DELIVERED       NORTH
1         2          244  2024-09-16 08:12:42  CANCELLED       SOUTH
2         3           99  2026-05-28 07:31:49     PLACED       SOUTH
3         4           86  2025-08-08 20:43:46    SHIPPED       SOUTH
4         5          398  2025-05-02 16:39:38     PLACED       SOUTH

In [ ]:
null_rows = random.sample(range(1000), 50)

for i in null_rows:
    orders.loc[i, "customer_id"] = None

In [ ]:
bad_dates = random.sample(range(1000), 30)

for i in bad_dates:

    d = fake.date()

    year, month, day = d.split("-")

    orders.loc[i, "order_date"] = (
        f"{day}-{month}-{year}"
    )

In [ ]:
duplicates = orders.sample(10)

orders = pd.concat(
    [orders, duplicates],
    ignore_index=True
)

In [ ]:
orders.shape

(1010, 5)

In [ ]:
orders.to_csv(
    "orders.csv",
    index=False
)

In [ ]:
from google.colab import files
files.download("orders.csv")

In [ ]:
order_items = []

for i in range(1, 3001):

    order_items.append({
        "item_id": i,
        "order_id": random.randint(1, 1000),
        "product_id": random.randint(1, 500),
        "quantity": random.randint(1, 5),
        "unit_price": random.randint(100, 5000),
        "discount_percent": random.randint(0, 100)
    })

order_items = pd.DataFrame(order_items)
order_items.head()

   item_id  order_id  product_id  quantity  unit_price  discount_percent
0        1       761         375         3        3719                14
1        2       924         316         4         771                54
2        3       474          69         5        4470                57
3        4       745         169         2        4176                20
4        5       312         413         5        4766                64

In [ ]:
valid_order_ids = orders["order_id"].tolist()

In [ ]:
order_items = []

for i in range(1, 3001):

    order_items.append({
        "item_id": i,
        "order_id": random.choice(valid_order_ids),
        "product_id": random.randint(1, 500),
        "quantity": random.randint(1, 5),
        "unit_price": random.randint(100, 5000),
        "discount_percent": random.randint(0, 100)
    })

order_items = pd.DataFrame(order_items)

In [ ]:
order_items.head()

   item_id  order_id  product_id  quantity  unit_price  discount_percent
0        1       935         428         2        4029                69
1        2       192         475         3        4063                61
2        3       524           4         5         944                50
3        4       312         447         3        4205                55
4        5        45         272         5        4541                87

In [ ]:
negative_rows = random.sample(range(3000), 90)

for i in negative_rows:
    order_items.loc[i, "quantity"] = -random.randint(1, 5)

In [ ]:
order_items[order_items["quantity"] < 0].head()

     item_id  order_id  product_id  quantity  unit_price  discount_percent
16        17        48         306        -2         689                 0
39        40       467         350        -3        3027                10
108      109       963         490        -3        1925                28
126      127       703          71        -3        2472                11
155      156       554          87        -2        4185                47

In [ ]:
bad_rows = random.sample(range(3000), 50)

for i in bad_rows:
    order_items.loc[i, "order_id"] = random.randint(5000, 6000)

In [ ]:
order_items[
    order_items["order_id"] > 1000
].head()

     item_id  order_id  product_id  quantity  unit_price  discount_percent
14        15      5661         399         1        1991               100
19        20      5592         136         2        4181                18
83        84      5182         298         4        2753                33
86        87      5502          23         4        4238                 7
146      147      5053         138         1        4323                45

In [ ]:
bad_discount = random.sample(range(3000), 20)

for i in bad_discount:
    order_items.loc[i, "discount_percent"] = 120

In [ ]:
order_items[
    order_items["discount_percent"] > 100
].head()

     item_id  order_id  product_id  quantity  unit_price  discount_percent
311      312       187         213         5        1911               120
317      318       416         164         1        3234               120
393      394       790          89         2        4027               120
532      533       650           9         5        3672               120
542      543       809         130         5        2458               120

In [ ]:
duplicates = order_items.sample(20)

order_items = pd.concat(
    [order_items, duplicates],
    ignore_index=True
)

In [ ]:
order_items.shape

(3020, 6)

In [ ]:
order_items.to_csv(
    "order_items.csv",
    index=False
)

In [ ]:
from google.colab import files
files.download("order_items.csv")

In [ ]:
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)

Customers: (505, 5)
Products: (500, 5)
Orders: (1010, 5)
Order Items: (3020, 6)

In [ ]:
customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")

In [ ]:
print(customers.shape)
print(products.shape)
print(orders.shape)
print(order_items.shape)

(505, 5)
(500, 5)
(1010, 5)
(3020, 6)

In [ ]:
issues = []

In [ ]:
customers.duplicated().sum()

np.int64(5)

In [ ]:
issues.append(
    ["customers", "Duplicate Rows",
     customers.duplicated().sum()]
)

In [ ]:
customers = customers.drop_duplicates()

In [ ]:
invalid_emails = customers[
    ~customers["email"].str.contains(
        "@",
        na=False
    )
]

In [ ]:
invalid_emails.head()

,customer_id,customer_name,email,registration_date,customer_type
53,54,Jeffrey Thomas,invalidemail.com,2015-11-27,VIP
107,108,Sarah Cummings,invalidemail.com,2021-08-12,REGULAR
118,119,Michelle Brown,invalidemail.com,2017-04-17,VIP
123,124,Jeremiah Anderson,invalidemail.com,2014-11-16,PREMIUM
228,229,Cynthia Heath,invalidemail.com,2013-01-22,REGULAR

In [ ]:
issues.append(
    ["customers",
     "Invalid Emails",
     len(invalid_emails)]
)

In [ ]:
customers = customers[
    customers["email"].str.contains(
        "@",
        na=False
    )
]

In [ ]:
customers.shape

(490, 5)

In [ ]:
issues.append(
    ["products",
     "Duplicate Rows",
     products.duplicated().sum()]
)

products = products.drop_duplicates()

In [ ]:
products["product_name"] = (
    products["product_name"]
    .str.strip()
    .str.title()
)

In [ ]:
products.head()

   product_id product_name     category subcategory  cost_price
0           1        Break         Home      policy         397
1           2        Leave        Books        film         749
2           3        Scene         Home   establish         775
3           4         Yeah  Electronics        hair        2169
4           5         Main  Electronics         let        3613

In [ ]:
issues.append(
    ["orders",
     "Duplicate Rows",
     orders.duplicated().sum()]
)

orders = orders.drop_duplicates()

In [ ]:
orders["customer_id"].isnull().sum()

np.int64(50)

In [ ]:
issues.append(
    ["orders",
     "Null Customer IDs",
     orders["customer_id"]
     .isnull()
     .sum()]
)

In [ ]:
orders = orders.dropna(
    subset=["customer_id"]
)

In [ ]:
orders["order_date"] = (
    pd.to_datetime(
        orders["order_date"],
        errors="coerce"
    )
)

In [ ]:
orders["order_date"].isnull().sum()

np.int64(55)

In [ ]:
issues.append(
    ["orders",
     "Invalid Dates",
     orders["order_date"]
     .isnull()
     .sum()]
)

In [ ]:
orders = orders.dropna(
    subset=["order_date"]
)

In [ ]:
issues.append(
    ["order_items",
     "Duplicate Rows",
     order_items.duplicated().sum()]
)

order_items = (
    order_items
    .drop_duplicates()
)

In [ ]:
order_items[
    order_items["quantity"] < 0
].shape

(90, 6)

In [ ]:
issues.append(
    ["order_items",
     "Negative Quantity",
     len(
         order_items[
             order_items["quantity"] < 0
         ]
     )]
)

In [ ]:
order_items = order_items[
    order_items["quantity"] > 0
]

In [ ]:
order_items[
    order_items[
        "discount_percent"
    ] > 100
]

      item_id  order_id  product_id  quantity  unit_price  discount_percent
311       312       187         213         5        1911               120
317       318       416         164         1        3234               120
393       394       790          89         2        4027               120
532       533       650           9         5        3672               120
542       543       809         130         5        2458               120
707       708       898         403         4        4981               120
783       784        62         431         1        1528               120
1205     1206      5445         340         2        4175               120
1281     1282        43         352         2        4792               120
1364     1365       332         371         3        4204               120
1926     1927       135          87         5        1538               120
2117     2118       455         469         2        2274               120
2308     2309       221         322         4        3248               120
2482     2483       252         143         1        1817               120
2553     2554       250         102         5        1226               120
2719     2720       543         466         5        1937               120
2780     2781       301         247         5        1826               120
2854     2855       258         457         4        2193               120
2879     2880       982          86         5        2380               120

In [ ]:
issues.append(
    ["order_items",
     "Discount >100",
     len(
         order_items[
             order_items[
                 "discount_percent"
             ] > 100
         ]
     )]
)

In [ ]:
order_items = order_items[
    order_items[
        "discount_percent"
    ] <= 100
]

In [ ]:
bad_orders = order_items[
    ~order_items["order_id"]
    .isin(
        orders["order_id"]
    )
]

In [ ]:
len(bad_orders)

340

In [ ]:
issues.append(
    ["order_items",
     "Invalid Order IDs",
     len(bad_orders)]
)

In [ ]:
order_items = order_items[
    order_items["order_id"]
    .isin(
        orders["order_id"]
    )
]

In [ ]:
issues_report = pd.DataFrame(
    issues,
    columns=[
        "table",
        "issue",
        "count"
    ]
)

issues_report

         table              issue  count
0    customers     Duplicate Rows      5
1    customers     Invalid Emails     10
2     products     Duplicate Rows      0
3       orders     Duplicate Rows     10
4       orders  Null Customer IDs     50
5       orders      Invalid Dates     55
6  order_items     Duplicate Rows     20
7  order_items  Negative Quantity     90
8  order_items      Discount >100     19
9  order_items  Invalid Order IDs    340

In [ ]:
customers.to_csv(
    "customers_clean.csv",
    index=False
)

products.to_csv(
    "products_clean.csv",
    index=False
)

orders.to_csv(
    "orders_clean.csv",
    index=False
)

order_items.to_csv(
    "order_items_clean.csv",
    index=False
)

issues_report.to_csv(
    "issues_report.csv",
    index=False
)

In [ ]:
from google.colab import files

files.download('customers_clean.csv')
files.download('products_clean.csv')
files.download('orders_clean.csv')
files.download('order_items_clean.csv')
files.download('issues_report.csv')

In [ ]:
import sqlite3

In [ ]:
conn = sqlite3.connect("ecommerce.db")

In [ ]:
conn

In [ ]:
customers.to_sql(
    "customers",
    conn,
    if_exists="replace",
    index=False
)

490

In [ ]:
products.to_sql(
    "products",
    conn,
    if_exists="replace",
    index=False
)

500

In [ ]:
orders.to_sql(
    "orders",
    conn,
    if_exists="replace",
    index=False
)

895

In [ ]:
order_items.to_sql(
    "order_items",
    conn,
    if_exists="replace",
    index=False
)

2551

In [ ]:
pd.read_sql(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    """,
    conn
)

          name
0    customers
1     products
2       orders
3  order_items

In [ ]:
pd.read_sql(
    "SELECT COUNT(*) AS rows FROM customers",
    conn
)

   rows
0   490

In [ ]:
pd.read_sql(
    "SELECT COUNT(*) AS rows FROM products",
    conn
)

   rows
0   500

In [ ]:
for table in [
    "customers",
    "products",
    "orders",
    "order_items"
]:
    query = f"""
    SELECT COUNT(*)
    AS rows
    FROM {table}
    """

    print(table)
    print(
        pd.read_sql(
            query,
            conn
        )
    )

customers
   rows
0   490
products
   rows
0   500
orders
   rows
0   895
order_items
   rows
0  2551

In [ ]:
pd.read_sql(
    """
    SELECT COUNT(*)
    FROM orders o
    LEFT JOIN customers c
    ON o.customer_id =
       c.customer_id
    WHERE c.customer_id
          IS NULL
    """,
    conn
)

   COUNT(*)
0        12

In [ ]:
valid_customer_ids = customers["customer_id"]

orders = orders[
    orders["customer_id"].isin(valid_customer_ids)
]

In [ ]:
orders.to_sql(
    "orders",
    conn,
    if_exists="replace",
    index=False
)

883

In [ ]:
pd.read_sql(
    """
    SELECT COUNT(*)
    FROM orders o
    LEFT JOIN customers c
    ON o.customer_id = c.customer_id
    WHERE c.customer_id IS NULL
    """,
    conn
)

   COUNT(*)
0         0

In [ ]:
# order_items → orders
pd.read_sql("""
SELECT COUNT(*)
FROM order_items oi
LEFT JOIN orders o
ON oi.order_id = o.order_id
WHERE o.order_id IS NULL
""", conn)

   COUNT(*)
0        34

In [ ]:
# order_items → products
pd.read_sql("""
SELECT COUNT(*)
FROM order_items oi
LEFT JOIN products p
ON oi.product_id = p.product_id
WHERE p.product_id IS NULL
""", conn)

   COUNT(*)
0         0

In [ ]:
valid_order_ids = orders["order_id"]

In [ ]:
order_items = order_items[
    order_items["order_id"].isin(valid_order_ids)
]

In [ ]:
order_items.to_sql(
    "order_items",
    conn,
    if_exists="replace",
    index=False
)

2517

In [ ]:
pd.read_sql("""
SELECT COUNT(*)
FROM order_items oi
LEFT JOIN orders o
ON oi.order_id = o.order_id
WHERE o.order_id IS NULL
""", conn)

   COUNT(*)
0         0

In [ ]:
orders.to_csv(
    "orders_clean.csv",
    index=False
)

order_items.to_csv(
    "order_items_clean.csv",
    index=False
)

In [ ]:
from google.colab import files

files.download("orders_clean.csv")
files.download("order_items_clean.csv")

In [ ]:
from google.colab import files
files.download(
    "ecommerce.db"
)

In [ ]:
customers.shape
products.shape
orders.shape
order_items.shape

(2517, 6)

In [ ]:
pd.read_sql(
"""
SELECT name
FROM sqlite_master
WHERE type='table'
""",
conn
)

          name
0    customers
1     products
2       orders
3  order_items

In [2]:
import pandas as pd

In [3]:
pd

In [5]:
import sqlite3
conn = sqlite3.connect("ecommerce.db")

In [8]:
import pandas as pd

customers = pd.read_csv("customers_clean.csv")
products = pd.read_csv("products_clean.csv")
orders = pd.read_csv("orders_clean.csv")
order_items = pd.read_csv("order_items_clean.csv")

In [9]:
import sqlite3
conn = sqlite3.connect("ecommerce.db")

customers.to_sql("customers", conn,
                 if_exists="replace",
                 index=False)

products.to_sql("products", conn,
                if_exists="replace",
                index=False)

orders.to_sql("orders", conn,
              if_exists="replace",
              index=False)

order_items.to_sql("order_items", conn,
                   if_exists="replace",
                   index=False)

2517

In [10]:
import pandas as pd
import sqlite3

pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

          name
0    customers
1     products
2       orders
3  order_items

In [11]:
conn

In [15]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

          name
0    customers
1     products
2       orders
3  order_items

#Query 1: Total Revenue per Category

In [16]:
pd.read_sql("""
SELECT
    p.category,
    ROUND(
        SUM(
            oi.quantity
            * oi.unit_price
            * (1 - oi.discount_percent/100.0)
        ),
        2
    ) AS revenue
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY revenue DESC
""", conn)

      category     revenue
0         Home  2634829.52
1     Clothing  2346317.66
2  Electronics  2309138.40
3        Books  2258681.28

#Query 2: Top 10 Customers by Total Order Value

In [17]:
pd.read_sql("""
SELECT
    c.customer_id,
    c.customer_name,
    ROUND(
        SUM(
            oi.quantity
            * oi.unit_price
            * (1 - oi.discount_percent/100.0)
        ),
        2
    ) AS total_revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY
    c.customer_id,
    c.customer_name
ORDER BY total_revenue DESC
LIMIT 10
""", conn)

   customer_id   customer_name  total_revenue
0          391   Bryan Cochran      122647.63
1          282    Daniel Allen      113868.28
2          244     Bailey Webb      111655.18
3          423  Steven Stanley      101114.64
4          258   Kayla Kennedy       86473.57
5           27   Kenneth Smith       84846.78
6          465    Angela Smith       84594.64
7           64     Paul Miller       80579.79
8          329   Michael Ponce       79857.03
9          426   Michael Combs       75206.30

#Query 3: Month-wise Order Count

In [18]:
pd.read_sql("""
SELECT
    strftime('%Y-%m', order_date)
    AS month,
    COUNT(*) AS total_orders
FROM orders
GROUP BY month
ORDER BY month
""", conn)

      month  total_orders
0   2024-07            23
1   2024-08            32
2   2024-09            35
3   2024-10            27
4   2024-11            40
5   2024-12            41
6   2025-01            38
7   2025-02            42
8   2025-03            50
9   2025-04            42
10  2025-05            32
11  2025-06            27
12  2025-07            28
13  2025-08            47
14  2025-09            42
15  2025-10            34
16  2025-11            29
17  2025-12            43
18  2026-01            40
19  2026-02            29
20  2026-03            51
21  2026-04            40
22  2026-05            37
23  2026-06            26
24  2026-07             8

#Query 4: Customers Who Placed Orders But Never Had Any Item Delivered

In [19]:
pd.read_sql("""
SELECT DISTINCT
    c.customer_id,
    c.customer_name
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
WHERE c.customer_id NOT IN
(
    SELECT DISTINCT
        o.customer_id
    FROM orders o
    WHERE o.status = 'DELIVERED'
)
""", conn)

     customer_id      customer_name
0              2    Joshua Gonzalez
1              5      Michael Brown
2              7     Debra Williams
3              9       Jose Salazar
4             10  Timothy Gutierrez
..           ...                ...
252          491         Megan Ruiz
253          493   Audrey Jefferson
254          495        Eric Miller
255          498     David Castillo
256          499         Dana Dixon

[257 rows x 2 columns]

#Query 5: Products Having More Returns Than Purchases

In [20]:
pd.read_sql("""
SELECT
    p.product_name,
    SUM(
        CASE
        WHEN oi.quantity < 0
        THEN ABS(oi.quantity)
        ELSE 0
        END
    ) AS returned,
    SUM(
        CASE
        WHEN oi.quantity > 0
        THEN oi.quantity
        ELSE 0
        END
    ) AS purchased
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY
    p.product_id,
    p.product_name
HAVING returned > purchased
""", conn)

Empty DataFrame
Columns: [product_name, returned, purchased]
Index: []

#Query 6: Return Rate per Category

In [21]:
pd.read_sql("""
SELECT
    p.category,
    ROUND(
        100.0 *
        SUM(
            CASE
            WHEN oi.quantity < 0
            THEN ABS(oi.quantity)
            ELSE 0
            END
        )
        /
        SUM(ABS(oi.quantity)),
        2
    ) AS return_rate
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.category
""", conn)

      category  return_rate
0        Books          0.0
1     Clothing          0.0
2  Electronics          0.0
3         Home          0.0

#Query 1: Rank Customers by Lifetime Value

In [22]:
pd.read_sql("""
WITH customer_revenue AS
(
    SELECT
        c.customer_id,
        c.customer_name,
        ROUND(
            SUM(
                oi.quantity *
                oi.unit_price *
                (1 - oi.discount_percent/100.0)
            ),
            2
        ) AS lifetime_value
    FROM customers c
    JOIN orders o
    ON c.customer_id = o.customer_id
    JOIN order_items oi
    ON o.order_id = oi.order_id
    GROUP BY
        c.customer_id,
        c.customer_name
)

SELECT *,
       DENSE_RANK() OVER(
           ORDER BY lifetime_value DESC
       ) AS customer_rank
FROM customer_revenue
LIMIT 20
""", conn)

    customer_id    customer_name  lifetime_value  customer_rank
0           391    Bryan Cochran       122647.63              1
1           282     Daniel Allen       113868.28              2
2           244      Bailey Webb       111655.18              3
3           423   Steven Stanley       101114.64              4
4           258    Kayla Kennedy        86473.57              5
5            27    Kenneth Smith        84846.78              6
6           465     Angela Smith        84594.64              7
7            64      Paul Miller        80579.79              8
8           329    Michael Ponce        79857.03              9
9           426    Michael Combs        75206.30             10
10          385      Dale Arnold        73175.60             11
11           62      James Payne        72496.97             12
12          482   Nicole Morales        69409.85             13
13          313  Patrick Stewart        68438.96             14
14          230   Mrs. Wendy Lee        68016.95             15
15          421  Heather Hubbard        67852.89             16
16          386     Todd Hopkins        66788.07             17
17          143   Andrew Montoya        65918.92             18
18          203   Stacy Erickson        63836.24             19
19          159       Sophia May        63803.68             20

#Query 2: Running Revenue by Month

In [23]:
pd.read_sql("""
WITH monthly_revenue AS
(
    SELECT
        strftime('%Y-%m', o.order_date) AS month,
        ROUND(
            SUM(
                oi.quantity *
                oi.unit_price *
                (1 - oi.discount_percent/100.0)
            ),
            2
        ) AS revenue
    FROM orders o
    JOIN order_items oi
    ON o.order_id = oi.order_id
    GROUP BY month
)

SELECT
    month,
    revenue,
    SUM(revenue)
    OVER(
        ORDER BY month
    ) AS running_total
FROM monthly_revenue
""", conn)

      month    revenue  running_total
0   2024-07  248739.89      248739.89
1   2024-08  365190.95      613930.84
2   2024-09  395487.44     1009418.28
3   2024-10  333027.27     1342445.55
4   2024-11  483448.74     1825894.29
5   2024-12  423714.45     2249608.74
6   2025-01  464677.69     2714286.43
7   2025-02  468392.98     3182679.41
8   2025-03  490690.19     3673369.60
9   2025-04  463261.17     4136630.77
10  2025-05  303800.88     4440431.65
11  2025-06  348134.31     4788565.96
12  2025-07  178016.59     4966582.55
13  2025-08  457383.12     5423965.67
14  2025-09  444646.97     5868612.64
15  2025-10  347712.00     6216324.64
16  2025-11  400893.79     6617218.43
17  2025-12  503974.71     7121193.14
18  2026-01  397229.51     7518422.65
19  2026-02  255869.71     7774292.36
20  2026-03  481589.53     8255881.89
21  2026-04  396988.27     8652870.16
22  2026-05  423036.57     9075906.73
23  2026-06  351656.39     9427563.12
24  2026-07  121403.74     9548966.86

#Query 3: Moving Average Revenue

In [24]:
pd.read_sql("""
WITH monthly_revenue AS
(
    SELECT
        strftime('%Y-%m', o.order_date) AS month,
        ROUND(
            SUM(
                oi.quantity *
                oi.unit_price *
                (1 - oi.discount_percent/100.0)
            ),
            2
        ) AS revenue
    FROM orders o
    JOIN order_items oi
    ON o.order_id = oi.order_id
    GROUP BY month
)

SELECT
    month,
    revenue,
    ROUND(
        AVG(revenue)
        OVER(
            ORDER BY month
            ROWS BETWEEN
            2 PRECEDING
            AND CURRENT ROW
        ),
        2
    ) AS moving_average
FROM monthly_revenue
""", conn)

      month    revenue  moving_average
0   2024-07  248739.89       248739.89
1   2024-08  365190.95       306965.42
2   2024-09  395487.44       336472.76
3   2024-10  333027.27       364568.55
4   2024-11  483448.74       403987.82
5   2024-12  423714.45       413396.82
6   2025-01  464677.69       457280.29
7   2025-02  468392.98       452261.71
8   2025-03  490690.19       474586.95
9   2025-04  463261.17       474114.78
10  2025-05  303800.88       419250.75
11  2025-06  348134.31       371732.12
12  2025-07  178016.59       276650.59
13  2025-08  457383.12       327844.67
14  2025-09  444646.97       360015.56
15  2025-10  347712.00       416580.70
16  2025-11  400893.79       397750.92
17  2025-12  503974.71       417526.83
18  2026-01  397229.51       434032.67
19  2026-02  255869.71       385691.31
20  2026-03  481589.53       378229.58
21  2026-04  396988.27       378149.17
22  2026-05  423036.57       433871.46
23  2026-06  351656.39       390560.41
24  2026-07  121403.74       298698.90

#Query 4: Monthly Growth Rate Using CTE

In [25]:
pd.read_sql("""
WITH monthly_revenue AS
(
    SELECT
        strftime('%Y-%m', o.order_date) AS month,
        ROUND(
            SUM(
                oi.quantity *
                oi.unit_price *
                (1 - oi.discount_percent/100.0)
            ),
            2
        ) AS revenue
    FROM orders o
    JOIN order_items oi
    ON o.order_id = oi.order_id
    GROUP BY month
)

SELECT
    month,
    revenue,
    revenue
    -
    LAG(revenue)
    OVER(
        ORDER BY month
    ) AS growth
FROM monthly_revenue
""", conn)

      month    revenue     growth
0   2024-07  248739.89        NaN
1   2024-08  365190.95  116451.06
2   2024-09  395487.44   30296.49
3   2024-10  333027.27  -62460.17
4   2024-11  483448.74  150421.47
5   2024-12  423714.45  -59734.29
6   2025-01  464677.69   40963.24
7   2025-02  468392.98    3715.29
8   2025-03  490690.19   22297.21
9   2025-04  463261.17  -27429.02
10  2025-05  303800.88 -159460.29
11  2025-06  348134.31   44333.43
12  2025-07  178016.59 -170117.72
13  2025-08  457383.12  279366.53
14  2025-09  444646.97  -12736.15
15  2025-10  347712.00  -96934.97
16  2025-11  400893.79   53181.79
17  2025-12  503974.71  103080.92
18  2026-01  397229.51 -106745.20
19  2026-02  255869.71 -141359.80
20  2026-03  481589.53  225719.82
21  2026-04  396988.27  -84601.26
22  2026-05  423036.57   26048.30
23  2026-06  351656.39  -71380.18
24  2026-07  121403.74 -230252.65

#Query 5: Customer Order Sequence

In [26]:
pd.read_sql("""
SELECT
    customer_id,
    order_id,
    order_date,
    ROW_NUMBER()
    OVER(
        PARTITION BY customer_id
        ORDER BY order_date
    ) AS order_number
FROM orders
LIMIT 30
""", conn)

    customer_id  order_id           order_date  order_number
0           1.0       516  2024-10-23 23:27:09             1
1           1.0       852  2025-04-23 21:18:58             2
2           1.0       764  2026-01-06 05:54:15             3
3           2.0       456  2024-08-02 14:30:42             1
4           4.0       395  2024-08-25 04:34:28             1
5           4.0        30  2026-03-04 01:27:50             2
6           5.0       400  2025-03-19 14:27:01             1
7           6.0       598  2025-02-19 22:02:13             1
8           6.0         1  2025-05-01 09:16:57             2
9           6.0       433  2026-01-17 22:08:15             3
10          7.0       308  2026-07-02 11:15:00             1
11          8.0       536  2024-12-10 16:46:43             1
12          9.0       313  2026-01-09 15:03:18             1
13         10.0       401  2025-05-09 03:23:53             1
14         10.0       655  2025-07-21 21:52:17             2
15         11.0       892  2025-04-08 06:48:50             1
16         13.0        42  2025-02-04 19:27:55             1
17         13.0       613  2025-08-28 18:28:44             2
18         13.0       239  2026-04-04 01:02:43             3
19         13.0       788  2026-04-14 05:47:39             4
20         14.0       423  2025-04-21 19:54:53             1
21         14.0       493  2025-10-29 10:06:06             2
22         15.0       208  2026-01-03 15:11:07             1
23         16.0       571  2024-11-03 01:37:24             1
24         16.0       279  2026-03-14 23:47:00             2
25         16.0       457  2026-04-21 18:39:11             3
26         17.0        48  2026-02-28 01:39:19             1
27         20.0       990  2024-11-29 00:24:34             1
28         20.0       205  2025-11-07 14:18:47             2
29         22.0       489  2025-03-08 02:38:39             1

#Query 1: Find Cohort Month of Each Customer

In [27]:
pd.read_sql("""
WITH first_purchase AS
(
    SELECT
        customer_id,
        MIN(strftime('%Y-%m', order_date))
        AS cohort_month
    FROM orders
    GROUP BY customer_id
)

SELECT *
FROM first_purchase
ORDER BY cohort_month;
""", conn)

     customer_id cohort_month
0           35.0      2024-07
1           46.0      2024-07
2           55.0      2024-07
3           93.0      2024-07
4          131.0      2024-07
..           ...          ...
401        149.0      2026-06
402        389.0      2026-06
403          7.0      2026-07
404         26.0      2026-07
405         29.0      2026-07

[406 rows x 2 columns]

#Query 2: Cohort Size

In [28]:
pd.read_sql("""
WITH first_purchase AS
(
    SELECT
        customer_id,
        MIN(strftime('%Y-%m', order_date))
        AS cohort_month
    FROM orders
    GROUP BY customer_id
)

SELECT
    cohort_month,
    COUNT(*) AS total_customers
FROM first_purchase
GROUP BY cohort_month
ORDER BY cohort_month;
""", conn)

   cohort_month  total_customers
0       2024-07               22
1       2024-08               29
2       2024-09               31
3       2024-10               19
4       2024-11               29
5       2024-12               25
6       2025-01               28
7       2025-02               25
8       2025-03               28
9       2025-04               19
10      2025-05               15
11      2025-06               13
12      2025-07               11
13      2025-08               20
14      2025-09               13
15      2025-10               11
16      2025-11                8
17      2025-12               12
18      2026-01               10
19      2026-02                9
20      2026-03               10
21      2026-04                8
22      2026-05                6
23      2026-06                2
24      2026-07                3

#Query 3: Monthly Retention

In [29]:
pd.read_sql("""
WITH first_purchase AS
(
    SELECT
        customer_id,
        MIN(strftime('%Y-%m', order_date))
        AS cohort_month
    FROM orders
    GROUP BY customer_id
)

SELECT
    fp.cohort_month,
    strftime('%Y-%m', o.order_date)
        AS order_month,
    COUNT(DISTINCT o.customer_id)
        AS active_customers
FROM orders o
JOIN first_purchase fp
ON o.customer_id = fp.customer_id
GROUP BY
    fp.cohort_month,
    order_month
ORDER BY
    fp.cohort_month,
    order_month;
""", conn)

    cohort_month order_month  active_customers
0        2024-07     2024-07                22
1        2024-07     2024-08                 2
2        2024-07     2024-09                 1
3        2024-07     2024-10                 1
4        2024-07     2024-11                 3
..           ...         ...               ...
236      2026-04     2026-04                 8
237      2026-05     2026-05                 6
238      2026-05     2026-06                 1
239      2026-06     2026-06                 2
240      2026-07     2026-07                 3

[241 rows x 3 columns]

#Query 4: Repeat vs One-Time Customers

In [30]:
pd.read_sql("""
WITH customer_orders AS
(
    SELECT
        customer_id,
        COUNT(*) AS total_orders
    FROM orders
    GROUP BY customer_id
)

SELECT
    CASE
        WHEN total_orders = 1
        THEN 'One-Time'
        ELSE 'Repeat'
    END AS customer_type,
    COUNT(*) AS customers
FROM customer_orders
GROUP BY customer_type;
""", conn)

  customer_type  customers
0      One-Time        148
1        Repeat        258

#Query 5: Churned Customers

In [31]:
pd.read_sql("""
SELECT
    customer_id,
    MAX(order_date)
        AS last_order_date
FROM orders
GROUP BY customer_id
HAVING julianday('now')
       -
       julianday(MAX(order_date))
       > 90;
""", conn)

     customer_id      last_order_date
0            1.0  2026-01-06 05:54:15
1            2.0  2024-08-02 14:30:42
2            4.0  2026-03-04 01:27:50
3            5.0  2025-03-19 14:27:01
4            6.0  2026-01-17 22:08:15
..           ...                  ...
310        493.0  2026-03-31 17:21:32
311        495.0  2025-03-08 06:47:38
312        496.0  2025-04-29 13:11:37
313        498.0  2025-08-02 06:06:01
314        499.0  2025-06-03 01:47:15

[315 rows x 2 columns]

In [33]:
%%writefile report_cli.py

Writing report_cli.py

In [36]:
%%writefile report_cli.py
import sqlite3
import pandas as pd
import argparse

# rest of the code...
import sqlite3
import pandas as pd
import argparse

conn = sqlite3.connect("ecommerce.db")

parser = argparse.ArgumentParser(
    description="E-commerce Analytics Reports"
)

parser.add_argument(
    "--report",
    type=str,
    required=True,
    help="revenue, top_customers, retention"
)

args = parser.parse_args()

if args.report == "revenue":

    query = """
    SELECT
        p.category,
        ROUND(
            SUM(
                oi.quantity *
                oi.unit_price *
                (1 - oi.discount_percent/100.0)
            ),
            2
        ) AS revenue
    FROM order_items oi
    JOIN products p
    ON oi.product_id = p.product_id
    GROUP BY p.category
    ORDER BY revenue DESC
    """

    print(pd.read_sql(query, conn))

elif args.report == "top_customers":

    query = """
    SELECT
        c.customer_id,
        c.customer_name,
        ROUND(
            SUM(
                oi.quantity *
                oi.unit_price *
                (1 - oi.discount_percent/100.0)
            ),
            2
        ) AS total_revenue
    FROM customers c
    JOIN orders o
    ON c.customer_id = o.customer_id
    JOIN order_items oi
    ON o.order_id = oi.order_id
    GROUP BY
        c.customer_id,
        c.customer_name
    ORDER BY total_revenue DESC
    LIMIT 10
    """

    print(pd.read_sql(query, conn))

elif args.report == "retention":

    query = """
    WITH first_purchase AS
    (
        SELECT
            customer_id,
            MIN(strftime('%Y-%m', order_date))
            AS cohort_month
        FROM orders
        GROUP BY customer_id
    )

    SELECT
        fp.cohort_month,
        strftime('%Y-%m', o.order_date)
        AS order_month,
        COUNT(DISTINCT o.customer_id)
        AS active_customers
    FROM orders o
    JOIN first_purchase fp
    ON o.customer_id = fp.customer_id
    GROUP BY
        fp.cohort_month,
        order_month
    ORDER BY
        fp.cohort_month,
        order_month
    """

    print(pd.read_sql(query, conn))

else:
    print(
        "Invalid report name.\n"
        "Available reports:\n"
        "1. revenue\n"
        "2. top_customers\n"
        "3. retention"
    )

conn.close()

Overwriting report_cli.py

In [37]:
!ls

customers_clean.csv  issues_report.csv	    orders_clean.csv	report_cli.py
ecommerce.db	     order_items_clean.csv  products_clean.csv	sample_data

In [38]:
!python report_cli.py --report revenue

      category     revenue
0         Home  2634829.52
1     Clothing  2346317.66
2  Electronics  2309138.40
3        Books  2258681.28

In [39]:
!python report_cli.py --report top_customers

   customer_id   customer_name  total_revenue
0          391   Bryan Cochran      122647.63
1          282    Daniel Allen      113868.28
2          244     Bailey Webb      111655.18
3          423  Steven Stanley      101114.64
4          258   Kayla Kennedy       86473.57
5           27   Kenneth Smith       84846.78
6          465    Angela Smith       84594.64
7           64     Paul Miller       80579.79
8          329   Michael Ponce       79857.03
9          426   Michael Combs       75206.30

In [40]:
!python report_cli.py --report retention

    cohort_month order_month  active_customers
0        2024-07     2024-07                22
1        2024-07     2024-08                 2
2        2024-07     2024-09                 1
3        2024-07     2024-10                 1
4        2024-07     2024-11                 3
..           ...         ...               ...
236      2026-04     2026-04                 8
237      2026-05     2026-05                 6
238      2026-05     2026-06                 1
239      2026-06     2026-06                 2
240      2026-07     2026-07                 3

[241 rows x 3 columns]

#Query 1: Purchase Frequency Segmentation

In [41]:
pd.read_sql("""
WITH customer_orders AS
(
    SELECT
        customer_id,
        COUNT(*) AS total_orders
    FROM orders
    GROUP BY customer_id
)

SELECT
    customer_id,
    total_orders,
    CASE
        WHEN total_orders = 1
            THEN 'One-Time'
        WHEN total_orders BETWEEN 2 AND 5
            THEN 'Occasional'
        ELSE 'Loyal'
    END AS frequency_segment
FROM customer_orders
ORDER BY total_orders DESC;
""", conn)

     customer_id  total_orders frequency_segment
0          423.0             8             Loyal
1          143.0             7             Loyal
2           64.0             6             Loyal
3           87.0             6             Loyal
4          230.0             6             Loyal
..           ...           ...               ...
401        485.0             1          One-Time
402        491.0             1          One-Time
403        495.0             1          One-Time
404        496.0             1          One-Time
405        498.0             1          One-Time

[406 rows x 3 columns]

#Query 2: Spend Tier Segmentation

In [42]:
pd.read_sql("""
WITH customer_revenue AS
(
    SELECT
        c.customer_id,
        ROUND(
            SUM(
                oi.quantity *
                oi.unit_price *
                (1 - oi.discount_percent / 100.0)
            ),
            2
        ) AS total_spent
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY c.customer_id
)

SELECT
    customer_id,
    total_spent,
    CASE
        WHEN total_spent < 5000
            THEN 'Low'
        WHEN total_spent BETWEEN 5000 AND 20000
            THEN 'Medium'
        ELSE 'High'
    END AS spend_tier
FROM customer_revenue
ORDER BY total_spent DESC;
""", conn)

     customer_id  total_spent spend_tier
0            391    122647.63       High
1            282    113868.28       High
2            244    111655.18       High
3            423    101114.64       High
4            258     86473.57       High
..           ...          ...        ...
392          450       163.80        Low
393          279       149.80        Low
394          479       143.64        Low
395           43       120.00        Low
396           15        18.66        Low

[397 rows x 3 columns]

#Query 3: Complete RFM Analysis

In [43]:
pd.read_sql("""
WITH rfm AS
(
    SELECT
        c.customer_id,

        CAST(
            julianday('now')
            -
            julianday(
                MAX(o.order_date)
            )
            AS INTEGER
        ) AS recency,

        COUNT(DISTINCT o.order_id)
            AS frequency,

        ROUND(
            SUM(
                oi.quantity *
                oi.unit_price *
                (1 - oi.discount_percent / 100.0)
            ),
            2
        ) AS monetary

    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY c.customer_id
)

SELECT
    *,
    CASE
        WHEN frequency >= 5
             AND monetary >= 20000
            THEN 'VIP'

        WHEN frequency >= 2
            THEN 'Regular'

        ELSE 'At Risk'
    END AS customer_segment

FROM rfm
ORDER BY monetary DESC;
""", conn)

     customer_id  recency  frequency   monetary customer_segment
0            391       58          5  122647.63              VIP
1            282      203          6  113868.28              VIP
2            244       94          5  111655.18              VIP
3            423       16          8  101114.64              VIP
4            258       59          3   86473.57          Regular
..           ...      ...        ...        ...              ...
392          450      401          1     163.80          At Risk
393          279      705          1     149.80          At Risk
394          479      490          1     143.64          At Risk
395           43      611          1     120.00          At Risk
396           15      188          1      18.66          At Risk

[397 rows x 5 columns]

This project demonstrates the complete workflow of an e-commerce analytics system, starting from raw data generation and cleaning to advanced SQL analytics and business reporting. It provides practical experience in data engineering, SQL analytics, and data-driven decision-making.